name: "Make the maps"

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: "Install dev version of SimpleSDMLayers"
        run: julia --project -e 'import Pkg; Pkg.add(Pkg.PackageSpec(url="https://github.com/EcoJulia/SimpleSDMLayers.jl"))'
      - name: "Install other packages"
        run: julia --project -e "import Pkg; Pkg.instantiate(); Pkg.update()"
      - name: "Install and build PyPlot"
        run: julia --project -e 'ENV["PYTHON"]=""; import Pkg; Pkg.build(); using PyPlot'
      - name: "Prepare folders"
        run: |
          mkdir -p data
          mkdir -p figures
          mkdir -p dist/data
          mkdir -p dist/figures
      - name: "Get network metadata"
        run: julia --project scripts/01_get_metadata.jl
      - name: "Get interactions list"
        run: julia --project scripts/02_get_interactions.jl
      - name: "Get bioclim values"
        run: julia --project scripts/03_get_bioclim.jl
      - name: "Merge dataframes"
        run: julia --project scripts/04_merge_data.jl
      - name: "Make figures on database contents"
        run: julia --project scripts/05_db_content.jl
      - name: "Make figures on networks by biomes"
        run: julia --project scripts/06_whittaker.jl
      - name: "Make figures on spatial/bioclimatic distance"
        run: julia --project scripts/07_analog_maps.jl
      - name: "Make figures on PCA based on bioclim data"
        run: julia --project scripts/08_pca_bioclim.jl
      - name: "Copy assets"
        run: |
          cp figures/* dist/figures
          cp data/* dist/data
      - name: "GitHub Pages deployment"
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: "dist/"
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
