name: "Create website"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "ls"
        run: ls -lah
      - name: "Move"
        run: cd dist
      - name: "ls"
        run: ls -lah
